---
- name: create the docker image by ansible
  hosts: node-2
  become: true

  tasks:
    - name: pull official Node.js image from Docker Hub
      docker_image:
        name: mysql
        source: pull
